/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/admin.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Load: typeof import('./src/components/Load.vue')['default']
    QuizList: typeof import('./src/components/quizList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Student: typeof import('./src/components/Student.vue')['default']
    Studentdate: typeof import('./src/components/studentdate.vue')['default']
    StudentPaper: typeof import('./src/components/studentPaper.vue')['default']
    StudentPaperimg: typeof import('./src/components/studentPaperimg.vue')['default']
    StudentQuestion: typeof import('./src/components/studentQuestion.vue')['default']
    Teacher: typeof import('./src/components/Teacher.vue')['default']
    Teacherdate: typeof import('./src/components/teacherdate.vue')['default']
    TeacherGrade: typeof import('./src/components/TeacherGrade.vue')['default']
    TeacherPaper: typeof import('./src/components/teacherPaper.vue')['default']
    TeacherPaperimg: typeof import('./src/components/teacherPaperimg.vue')['default']
    TeacherQuizlist: typeof import('./src/components/teacherQuizlist.vue')['default']
    TeacherStudent: typeof import('./src/components/teacherStudent.vue')['default']
  }
}
